<section id="content-wrapper">
	<center><p style="margin-left:30px;margin-top:20px;color:rgb(77,145,123);font-size:14px"><span style="color:#292929;font-size:16px">Usage Disclaimer : </span> Use either Firefox or Internet Explorer for complete site functionality.If you prefer to use Chrome, please unblock the scripts before using the site.</p></center>
	<div id="login" style="height: 550px;margin-top:-50px">
		<div class="user-icon"></div>
		<div class="pass-icon"></div>
		<form name="login-form" class="login-form"
			action="<?php echo $this->baseUrl("index/index");?>" method="post">
			<div class="header">
				<h1>Login</h1>
				<span style="font-size:13px">Please use your credentials to log in below:</span>
			</div>
			<div class="content">
				<input name="username" type="text" class="input username"
					placeholder="Username" /> <input name="password" type="password"
					class="input password" placeholder="Password" />
			</div>
			<p style="font-size: 13px; color: red; margin-left: 30px;">
				<?php echo $this->error;?>
			</p>
			<div class="footer">
				<input type="submit" name="login" value="Login" class="button" />
			</div>
		</form>
	</div>
	<div class="clr"></div>
</section>

<script
	src="<?php echo $this->baseUrl("public/scripts/jquery.min.js");?>"></script>
<script type="text/javascript">
    $(document).ready(function() {
	    $(".username").focus(function() {
		    $(".user-icon").css("left","-48px");
	    });
	    $(".username").blur(function() {
		    $(".user-icon").css("left","0px");
	    });

	    $(".password").focus(function() {
		    $(".pass-icon").css("left","-48px");
	    });
	    $(".password").blur(function() {
		    $(".pass-icon").css("left","0px");
	    });
    });
</script>
</html>