<style>
	#home{
		float: right;
		font-size: 35px;
		color: rgb(77,145,123);
		padding-right: 10px;
		cursor:pointer;
	}
</style>
<div style="background:rgb(244,244,244);height:40px;">
	<i class="icon-home" id="home" onclick="location.href='<?php echo $this->baseUrl("index/getssndetails")?>'"></i>
</div>
<div style="text-align:center;width:500px;margin:60px auto;">
	<h2 style="color:rgb(77,145,123)">Thank You for completing our survey</h2>
	<p>Thanks for completing our brief survey and submitting your valuable feedback. Your confidential answers will help in improving our data quality. </p>
</div>