<?php 
class Application_Model_Constants
{
	const PERM_SURVEY_USER = 1251199;
	const GATEKEEPER_STATUS_VALID = 1 ;
	const GATEKEEPER_STATUS_INVALIDIP = 4 ;
	const GATEKEEPER_STATUS_INVALIDCREDS = 5 ;
	const GATEKEEPER_STATUS_INVALID_SESSION = 6 ;
	const GATEKEEPER_STATUS_LOCKED = 7 ;
	const GATEKEEPER_STATUS_CODE_SENT = 10;
	const GATEKEEPER_STATUS_INVALID_CODE = 11;
}
?>